### ISSUE TITLE
[1pt] Create empty My profile - Setup (group task)

### ISSUE THREAD

**Issue by kerlos-bahaa** [kerlos-bahaa/Space-x#22]
- Create a route and a view component. Use `<NavLink />` for the page navigation links and style active class to indicate which section/page the user is currently on (underline active navigation link).
- This view should be empty - you will add content in separate tasks.

**Comment by rodrigopenayo98** [comment]
Hi @kerlos-bahaa,

Great job on this part of the project! Everything looks ready for us to merge it: ship it:
Congratulations! 🎉

Highlights:

All requested changes have been implemented successfully ✅
Optional suggestions:
Comments with the [OPTIONAL] prefix can be considered to further improve the code, although they are not essential for approval.
You may also want to consider:

Using the same pull request for subsequent reviews 👍🏿
Keep up the good work and happy coding! 👏👏👏

If you have any questions or concerns, feel free to leave them in the pull request thread. Remember to tag me in your question so I can receive the notification @rodrigopenayo98.
